name: Build Windows-Helper

on:
  push:
    branches:
      - main
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build PyInstaller
        run: pyinstaller windows-helper.spec

      - name: Copy Resources to Dist
        run: xcopy app\res dist\res\ /s /e /h

      - name: Copy Windows to Dist
        run: xcopy app\windows dist\windows\ /s /e /h
      
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
